"""Phase 2: Add Person, Employment, FinanceKYC, RatePlan, Document models

Revision ID: 16ae72943693
Revises: 06e276ae99bb
Create Date: 2026-01-21 16:06:33.649206

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '16ae72943693'
down_revision = '06e276ae99bb'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('persons',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('mobile', sa.String(), nullable=False),
    sa.Column('alt_mobile', sa.String(), nullable=True),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('dob', sa.Date(), nullable=True),
    sa.Column('stream', sa.Enum('MECH', 'CIVIL', 'ELEC', 'OTHER', name='stream'), nullable=True),
    sa.Column('stream_other', sa.String(), nullable=True),
    sa.Column('education', sa.Enum('DIPLOMA', 'DEGREE', 'ME', 'OTHER', name='education'), nullable=True),
    sa.Column('education_other', sa.String(), nullable=True),
    sa.Column('location', sa.String(), nullable=True),
    sa.Column('status', sa.Enum('DRAFT', 'SUBMITTED_TO_FINANCE', 'SENT_TO_HR', 'ACTIVE', name='personstatus'), nullable=False),
    sa.Column('created_by_user_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_persons_id'), 'persons', ['id'], unique=False)
    op.create_table('documents',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('person_id', sa.UUID(), nullable=False),
    sa.Column('stage', sa.Enum('OPERATION', 'FINANCE', 'HR', name='documentstage'), nullable=False),
    sa.Column('doc_name', sa.String(), nullable=False),
    sa.Column('file_key', sa.String(), nullable=False),
    sa.Column('mime_type', sa.String(), nullable=False),
    sa.Column('size_bytes', sa.BigInteger(), nullable=False),
    sa.Column('is_mandatory', sa.Boolean(), nullable=True),
    sa.Column('created_by_user_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['person_id'], ['persons.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_documents_id'), 'documents', ['id'], unique=False)
    op.create_table('employments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('person_id', sa.UUID(), nullable=False),
    sa.Column('employment_type', sa.Enum('PERMANENT', 'FREELANCER', 'CONTRACTUAL', name='employmenttype'), nullable=False),
    sa.Column('employee_code', sa.String(), nullable=True),
    sa.Column('company_id', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['company_master.id'], ),
    sa.ForeignKeyConstraint(['person_id'], ['persons.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_employments_employee_code'), 'employments', ['employee_code'], unique=True)
    op.create_index(op.f('ix_employments_id'), 'employments', ['id'], unique=False)
    op.create_table('finance_kyc',
    sa.Column('person_id', sa.UUID(), nullable=False),
    sa.Column('aadhaar', sa.String(), nullable=True),
    sa.Column('pan', sa.String(), nullable=True),
    sa.Column('bank_account_no', sa.String(), nullable=True),
    sa.Column('ifsc', sa.String(), nullable=True),
    sa.Column('bank_name', sa.String(), nullable=True),
    sa.Column('branch', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['person_id'], ['persons.id'], ),
    sa.PrimaryKeyConstraint('person_id')
    )
    op.create_table('rate_plans',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('person_id', sa.UUID(), nullable=False),
    sa.Column('plan_type', sa.Enum('MANDAY', 'MANMONTH', 'MONTHLY_SALARY', name='plantype'), nullable=False),
    sa.Column('amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('valid_from', sa.Date(), nullable=False),
    sa.Column('valid_to', sa.Date(), nullable=True),
    sa.Column('working_day_mode', sa.Enum('CALENDAR', 'WORKING_26', name='workingdaymode'), nullable=True),
    sa.Column('project_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['person_id'], ['persons.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['project_master.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_rate_plans_id'), 'rate_plans', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_rate_plans_id'), table_name='rate_plans')
    op.drop_table('rate_plans')
    op.drop_table('finance_kyc')
    op.drop_index(op.f('ix_employments_id'), table_name='employments')
    op.drop_index(op.f('ix_employments_employee_code'), table_name='employments')
    op.drop_table('employments')
    op.drop_index(op.f('ix_documents_id'), table_name='documents')
    op.drop_table('documents')
    op.drop_index(op.f('ix_persons_id'), table_name='persons')
    op.drop_table('persons')
    # ### end Alembic commands ###

