"""add_label_description_to_permissions

Revision ID: a6b947c61d27
Revises: ffff_add_intake_dept_to_person
Create Date: 2026-01-27 18:34:10.544791

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'a6b947c61d27'
down_revision = 'ffff_add_intake_dept_to_person'
branch_labels = None
depends_on = None


def _index_exists(table_name: str, index_name: str) -> bool:
    """Return True if the given index exists on the table (PostgreSQL-safe)."""
    bind = op.get_bind()
    inspector = sa.inspect(bind)
    indexes = inspector.get_indexes(table_name)
    return any(idx["name"] == index_name for idx in indexes)


def _access_grants_has_scope_value():
    """Return True if access_grants.scope_value column exists (PostgreSQL-safe)."""
    bind = op.get_bind()
    inspector = sa.inspect(bind)
    columns = [c["name"] for c in inspector.get_columns("access_grants")]
    return "scope_value" in columns


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###

    # Ensure access_grants.scope_value exists before altering it (Render-safe re-runs).
    if not _access_grants_has_scope_value():
        op.add_column(
            "access_grants",
            sa.Column("scope_value", sa.String(), nullable=True, server_default=sa.text("''")),
        )
    # Backfill NULLs so we can set NOT NULL (existing rows from partial runs).
    op.execute("UPDATE access_grants SET scope_value = '' WHERE scope_value IS NULL")
    op.alter_column(
        "access_grants",
        "scope_value",
        existing_type=sa.VARCHAR(),
        nullable=False,
    )

    op.alter_column('access_grants', 'ticket_id',
               existing_type=sa.UUID(),
               nullable=True)
    if not _index_exists('access_grants', 'ix_access_grants_expires_at'):
        op.create_index(op.f('ix_access_grants_expires_at'), 'access_grants', ['expires_at'], unique=False)
    if not _index_exists('access_grants', 'ix_access_grants_granted_to_user_id'):
        op.create_index(op.f('ix_access_grants_granted_to_user_id'), 'access_grants', ['granted_to_user_id'], unique=False)
    if not _index_exists('access_grants', 'ix_access_grants_id'):
        op.create_index(op.f('ix_access_grants_id'), 'access_grants', ['id'], unique=False)
    if not _index_exists('access_grants', 'ix_access_grants_person_id'):
        op.create_index(op.f('ix_access_grants_person_id'), 'access_grants', ['person_id'], unique=False)
    op.drop_column('access_grants', 'doc_category')
    op.drop_column('access_grants', 'document_ids')
    op.alter_column('audit_logs', 'action_metadata',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               existing_nullable=True)
    if not _index_exists('audit_logs', 'ix_audit_logs_id'):
        op.create_index(op.f('ix_audit_logs_id'), 'audit_logs', ['id'], unique=False)
    op.add_column('permissions', sa.Column('label', sa.String(), nullable=True))
    op.add_column('permissions', sa.Column('description', sa.String(), nullable=True))
    op.drop_index('ix_persons_activated_at', table_name='persons')
    if not _index_exists('ticket_attachments', 'ix_ticket_attachments_id'):
        op.create_index(op.f('ix_ticket_attachments_id'), 'ticket_attachments', ['id'], unique=False)
    if not _index_exists('ticket_comments', 'ix_ticket_comments_id'):
        op.create_index(op.f('ix_ticket_comments_id'), 'ticket_comments', ['id'], unique=False)
    op.drop_constraint('tickets_ticket_no_key', 'tickets', type_='unique')
    op.drop_index('ix_tickets_ticket_no', table_name='tickets')
    if not _index_exists('tickets', 'ix_tickets_ticket_no'):
        op.create_index(op.f('ix_tickets_ticket_no'), 'tickets', ['ticket_no'], unique=True)
    if not _index_exists('tickets', 'ix_tickets_id'):
        op.create_index(op.f('ix_tickets_id'), 'tickets', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_tickets_id'), table_name='tickets')
    op.drop_index(op.f('ix_tickets_ticket_no'), table_name='tickets')
    op.create_index('ix_tickets_ticket_no', 'tickets', ['ticket_no'], unique=False)
    op.create_unique_constraint('tickets_ticket_no_key', 'tickets', ['ticket_no'])
    op.drop_index(op.f('ix_ticket_comments_id'), table_name='ticket_comments')
    op.drop_index(op.f('ix_ticket_attachments_id'), table_name='ticket_attachments')
    op.create_index('ix_persons_activated_at', 'persons', ['activated_at'], unique=False)
    op.drop_column('permissions', 'description')
    op.drop_column('permissions', 'label')
    op.drop_index(op.f('ix_audit_logs_id'), table_name='audit_logs')
    op.alter_column('audit_logs', 'action_metadata',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True)
    op.add_column('access_grants', sa.Column('document_ids', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.add_column('access_grants', sa.Column('doc_category', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_index(op.f('ix_access_grants_person_id'), table_name='access_grants')
    op.drop_index(op.f('ix_access_grants_id'), table_name='access_grants')
    op.drop_index(op.f('ix_access_grants_granted_to_user_id'), table_name='access_grants')
    op.drop_index(op.f('ix_access_grants_expires_at'), table_name='access_grants')
    op.alter_column('access_grants', 'scope_value',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('access_grants', 'ticket_id',
               existing_type=sa.UUID(),
               nullable=False)
    # ### end Alembic commands ###
