"""add_label_description_to_permissions

Revision ID: a6b947c61d27
Revises: ffff_add_intake_dept_to_person
Create Date: 2026-01-27 18:34:10.544791

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'a6b947c61d27'
down_revision = 'ffff_add_intake_dept_to_person'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('access_grants', 'ticket_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.alter_column('access_grants', 'scope_value',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.create_index(op.f('ix_access_grants_expires_at'), 'access_grants', ['expires_at'], unique=False)
    op.create_index(op.f('ix_access_grants_granted_to_user_id'), 'access_grants', ['granted_to_user_id'], unique=False)
    op.create_index(op.f('ix_access_grants_id'), 'access_grants', ['id'], unique=False)
    op.create_index(op.f('ix_access_grants_person_id'), 'access_grants', ['person_id'], unique=False)
    op.drop_column('access_grants', 'doc_category')
    op.drop_column('access_grants', 'document_ids')
    op.alter_column('audit_logs', 'action_metadata',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               existing_nullable=True)
    op.create_index(op.f('ix_audit_logs_id'), 'audit_logs', ['id'], unique=False)
    op.add_column('permissions', sa.Column('label', sa.String(), nullable=True))
    op.add_column('permissions', sa.Column('description', sa.String(), nullable=True))
    op.drop_index('ix_persons_activated_at', table_name='persons')
    op.create_index(op.f('ix_ticket_attachments_id'), 'ticket_attachments', ['id'], unique=False)
    op.create_index(op.f('ix_ticket_comments_id'), 'ticket_comments', ['id'], unique=False)
    op.drop_constraint('tickets_ticket_no_key', 'tickets', type_='unique')
    op.drop_index('ix_tickets_ticket_no', table_name='tickets')
    op.create_index(op.f('ix_tickets_ticket_no'), 'tickets', ['ticket_no'], unique=True)
    op.create_index(op.f('ix_tickets_id'), 'tickets', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_tickets_id'), table_name='tickets')
    op.drop_index(op.f('ix_tickets_ticket_no'), table_name='tickets')
    op.create_index('ix_tickets_ticket_no', 'tickets', ['ticket_no'], unique=False)
    op.create_unique_constraint('tickets_ticket_no_key', 'tickets', ['ticket_no'])
    op.drop_index(op.f('ix_ticket_comments_id'), table_name='ticket_comments')
    op.drop_index(op.f('ix_ticket_attachments_id'), table_name='ticket_attachments')
    op.create_index('ix_persons_activated_at', 'persons', ['activated_at'], unique=False)
    op.drop_column('permissions', 'description')
    op.drop_column('permissions', 'label')
    op.drop_index(op.f('ix_audit_logs_id'), table_name='audit_logs')
    op.alter_column('audit_logs', 'action_metadata',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True)
    op.add_column('access_grants', sa.Column('document_ids', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.add_column('access_grants', sa.Column('doc_category', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_index(op.f('ix_access_grants_person_id'), table_name='access_grants')
    op.drop_index(op.f('ix_access_grants_id'), table_name='access_grants')
    op.drop_index(op.f('ix_access_grants_granted_to_user_id'), table_name='access_grants')
    op.drop_index(op.f('ix_access_grants_expires_at'), table_name='access_grants')
    op.alter_column('access_grants', 'scope_value',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('access_grants', 'ticket_id',
               existing_type=sa.UUID(),
               nullable=False)
    # ### end Alembic commands ###

